### PR TITLE
Enable partition labeling

### PR DESCRIPTION
**Pull request by martignoni**
Small enhancement to enable partition labeling.

### CODE REVIEW

**Comment by martignoni** [comment]
Hi,
Any chance that this feature gets into your project?
Cheers and thanks for it.
Nicolas

**Comment by aoakley** [comment]
Yes, just a lack of free time to check & test at the mo. Should have more
time after the next Cotswold Jam on 23 Sept, so this will probably go in
early Oct.

Probably.

-- 
Andrew Oakley andrew@aoakley.com

**Comment by martignoni** [comment]
Hi @aoakley,
Any news?
Cheers!

**Comment by aoakley** [comment]
Sorry for the delay - been busy.

**Comment by martignoni** [comment]
No problem. Many thanks!

**Pull request merged**
